/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManganRek;

import java.sql.*;
import javax.swing.JOptionPane;
import ManganRek.koneksi;
import java.awt.List;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.Stack;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author denny
 */
public class detailpesanan extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    login log = new login();

    String getadmin = log.getuser.toString();

    protected void aktif() {
        System.out.println("Coba" + getadmin);
        getusertxt.setText("Selamat Datang " + getadmin);

    }

    protected void kosong() {

    }

    protected void datatable() {
        Object[] Baris = {"ID PEMBELI", "ID MAKANAN", "USERNAME", "JUMLAH", "JUMLAH HARGA", "TANGGAL", "HASIL"};
        tabmode = new DefaultTableModel(null, Baris);
        tblstokbarang.setModel(tabmode);
        String sql = "select * from pembeli where username ='" + usertxt.getText() + "'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String id_pmbl = hasil.getString("id_pembeli");
                String id_mkn = hasil.getString("id_makanan");
                String user = hasil.getString("username");
                String jml = hasil.getString("jumlah");
                String tot = hasil.getString("jumlahharga");
                String tgl = hasil.getString("tanggal");
                String hsl = hasil.getString("hasil");
                String[] data = {id_pmbl, id_mkn, user, jml, tot, tgl, hsl};
                tabmode.addRow(data);
                System.out.println(data);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public detailpesanan(String para) {
        initComponents();
        aktif();
        usertxt.setText(para);
        datatable();
    }

    public detailpesanan() {
        initComponents();
        aktif();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstokbarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancel = new javax.swing.JToggleButton();
        btnExit = new javax.swing.JToggleButton();
        getusertxt = new javax.swing.JLabel();
        usertxt = new javax.swing.JLabel();
        idmkn = new javax.swing.JLabel();
        jmltxt = new javax.swing.JLabel();
        idpembelitxt = new javax.swing.JLabel();
        totaltxt = new javax.swing.JLabel();
        btnInput = new javax.swing.JToggleButton();
        tanggaltxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tblstokbarang.setBackground(new java.awt.Color(204, 204, 255));
        tblstokbarang.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        tblstokbarang.setForeground(new java.awt.Color(0, 0, 153));
        tblstokbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Alamat", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblstokbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstokbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstokbarang);

        jLabel7.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("pcs");

        jLabel4.setFont(new java.awt.Font("Nyala", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("DATA PESANAN ");

        cancel.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 0, 153));
        cancel.setText("Kembali");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(204, 204, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManganRek/images/close.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        getusertxt.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        getusertxt.setForeground(new java.awt.Color(0, 0, 153));
        getusertxt.setText("Selamat Datang ");

        usertxt.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        usertxt.setForeground(new java.awt.Color(0, 0, 153));
        usertxt.setText("user");

        idmkn.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        idmkn.setForeground(new java.awt.Color(204, 204, 255));
        idmkn.setText("id");

        jmltxt.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        jmltxt.setForeground(new java.awt.Color(0, 0, 153));
        jmltxt.setText("jumlah");

        idpembelitxt.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        idpembelitxt.setForeground(new java.awt.Color(204, 204, 255));
        idpembelitxt.setText("id");

        totaltxt.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        totaltxt.setForeground(new java.awt.Color(0, 0, 153));
        totaltxt.setText("total");

        btnInput.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        btnInput.setForeground(new java.awt.Color(0, 0, 153));
        btnInput.setText("Diterima");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        tanggaltxt.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        tanggaltxt.setForeground(new java.awt.Color(0, 0, 153));
        tanggaltxt.setText("tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(idpembelitxt)
                        .addGap(18, 18, 18)
                        .addComponent(idmkn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jmltxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39)
                        .addComponent(totaltxt)
                        .addGap(39, 39, 39)
                        .addComponent(tanggaltxt)
                        .addGap(24, 24, 24)
                        .addComponent(btnInput)
                        .addGap(18, 18, 18)
                        .addComponent(cancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(48, 48, 48)
                                .addComponent(getusertxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usertxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(getusertxt)
                        .addComponent(usertxt)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpembelitxt)
                    .addComponent(btnInput)
                    .addComponent(cancel)
                    .addComponent(idmkn)
                    .addComponent(jmltxt)
                    .addComponent(totaltxt)
                    .addComponent(tanggaltxt)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        Pemesanan pms = new Pemesanan(usertxt.getText());
        pms.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            this.dispose();
            login log = new login();
            log.setVisible(true);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        try {
            String sql = "update pembeli set id_makanan=?, username=?, jumlah=?, jumlahharga=?, tanggal=?, hasil=? where id_pembeli='" + idpembelitxt.getText() + "'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, idmkn.getText());
            stat.setString(2, usertxt.getText());
            stat.setString(3, jmltxt.getText());
            stat.setString(4, totaltxt.getText());
            stat.setString(5, tanggaltxt.getText());
            stat.setString(6, "Sudah Diterima");

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Terima Kasih");
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "DATA GAGAL DIUBAH" + e);
        }
    }//GEN-LAST:event_btnInputActionPerformed

    private void tblstokbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstokbarangMouseClicked
        int bar = tblstokbarang.getSelectedRow();
        String id_pbl = tabmode.getValueAt(bar, 0).toString();
        String id_mkn = tabmode.getValueAt(bar, 1).toString();
        String jml = tabmode.getValueAt(bar, 3).toString();
        String total = tabmode.getValueAt(bar, 4).toString();
        String tgl = tabmode.getValueAt(bar, 5).toString();

        idpembelitxt.setText(id_pbl);
        idmkn.setText(id_mkn);
        jmltxt.setText(jml);
        totaltxt.setText(total);
        tanggaltxt.setText(tgl);
    }//GEN-LAST:event_tblstokbarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailpesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailpesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JToggleButton btnInput;
    private javax.swing.JToggleButton cancel;
    private javax.swing.JLabel getusertxt;
    private javax.swing.JLabel idmkn;
    private javax.swing.JLabel idpembelitxt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jmltxt;
    private javax.swing.JLabel tanggaltxt;
    private javax.swing.JTable tblstokbarang;
    private javax.swing.JLabel totaltxt;
    private javax.swing.JLabel usertxt;
    // End of variables declaration//GEN-END:variables
}
